### ISSUE TITLE
Start Project

### ISSUE THREAD

**Issue by anandology** [pipalacademy/capstone#14]
As a user, I should be able to start a project by clicking on "Start Project" button.

After I click that I should see by first task "clone git repo" and when I make the first commit, the task should be completed.

This requires the git integration to be done.

## Config

- [x] config variable `git_base_url`
- [x] config variable `git_root_directory`
- [x] config variable `git_post_receive_token` 

## API 

- [ ] /api/webhooks/post-receive

## Task

- [x] setup_git_repo (initialize a git repo for a user)

## CLI

```
$ capstone-server user-projects -p rajdhani list
id | project | email | git_url | progress
```

```
$ capstone-server user-projects show --id 1
id: 
project: 
email: 
git_url: 
progress:
app_url: 
$ capstone-server user-projects show --user alice@example.com
```

```
$ capstone-server user-projects delete --user alice@example.com
```

- [x] list
- [x] show
- [x] delete

**Comment by nikochiko** [comment]
Why did we decide to run `setup_git_repo` as a task?
I think it might work to have it run synchronously only. That will also avoid the complexity of the "waiting-for-completion" state for user_project

**Comment by anandology** [comment]
How will you know if they have cloned it or not? 

Instead of saying "clone the repo and complete task 1", it is easier to track if they are two separate tasks.

**Comment by nikochiko** [comment]
Ah, I thought task here meant a queue task

**Comment by anandology** [comment]
I was wrong. `setup_git_rep` was meant to be an offline task. I didn't get the context when I replied earlier. 

Setting up git repo may take long time and there is no need for it to happen during the request/response cycle. That was the reason to suggest making it a task. If you think it would be easier to start doing that as part of the request cycle, go ahead and complete it, but make sure you come back to it later.

**Comment by nikochiko** [comment]
The post-receive hook needs the deployment part and checks part to be figured out before it can be run. I think it be better to come back to it after we do those two tasks.
