### ISSUE TITLE
Setup a staging instance

### ISSUE THREAD

**Issue by anandology** [pipalacademy/capstone#24]
Setup a staging instance to deploy capstone on every push.

## Tasks

**Provision a server**

- [x] create a new $5 linode 
- [x] configure DNS for  `capstone-staging.pipal.in` and  `git.capstone-staging.pipal.in`

**Setup Gitto**

- [x] create user gitto (without sudo)
- [x] clone gitto to /home/gitto/gitto
- [x] go build
- [x] mkdir /home/gitto/git
- [x] setup supervisor process for gitto with logs going to `/var/log/supevisor/gitto.log`

**Setup capstone**

- [x] create a user capstone (without sudo)
- [x] create postgres user capstone and a database capstone with user capstone as owner
- [x] setup supervisor for capstone gunicorn (logs go to /var/log/supervisor/capstone.log)
- [x] #29

**Setup Caddy**

- [x] setup site capstone-staging.pipal.in
- [x] setup site git.capstone-staging.pipal.in

**Setup github actions**

- [x] git push on capstone repo should update the staging deployment using PIPAL_BOT_SSH_KEY

**Comment by anandology** [comment]
Anand will provide the Oauth secrets

**Comment by anandology** [comment]
> Anand will provide the Oauth secrets

Shared with @nikochiko.

**Comment by nikochiko** [comment]
Done!

**Comment by nikochiko** [comment]
The redirect uri must be set to `https://capstone-staging.pipal.in/auth/google/callback` in google's oauth settings.

**Comment by anandology** [comment]
Can you change it it /login/google/callback ?
I have already configured that url.

**Comment by anandology** [comment]
Done.

Enabled

https://capstone-staging.pipal.in/auth/google/callback

Anand

**Comment by nikochiko** [comment]
Thanks! Closing this as donel
