### ISSUE TITLE
Capstone 0.1 Roadmap

### ISSUE THREAD

**Issue by anandology** [pipalacademy/capstone#7]
Let's plan a 0.1 release of capstone with the following features.

## Tech Stack

- Postgres DB
- Redis + RQ / tq (?)
- web.py db + simple schema migrations
- Flask 
- Kutty
- Pydantic
- pytest
- docker
- hamr (?) / Nomad

## Features

* capstone-checker to create a checker for your project (public repo + documentation + pypi?)
* capstonectl command to push a capstone project 
* Document the `capstone.yml` format
* Deploy checks of the project

**Comment by anandology** [comment]
# Tasks
## Tasks

- [ ] schema in postgres with multi-tenancy
- [ ] Dev setup (github actions, mypy, flake8) + deploy setup
- [ ] setup a staging instance with two instances (just empty home page with title)
- [ ] Create/updae and view projects (create/update on API, view on home page and details page)
- [ ] Project details page
- [ ] Login & Sigup - github/google login
- [ ] Git setup
- [ ] Start Project
- [ ] Reset Project
- [ ] Run checks on git push (post-receive hook, deployment and checks)

**Comment by anandology** [comment]
Open Issues:

- How do we authenticate authors when they push a project to capstone?
